{/* AUTH ACTIONS */}
export const AUTH_INIT = 'AUTH_INIT';
export const LOGIN_USER = 'LOGIN_USER';
export const LOGIN_USER_OAUTH = 'LOGIN_USER_OAUTH';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_FAIL = 'LOGIN_USER_FAIL';
export const LOGOUT_USER = 'LOGOUT_USER';
export const LOGOUT_USER_SUCCESS = 'LOGOUT_USER_SUCCESS'
export const USER_UPDATE_PROP = 'USER_UPDATE_PROP';

{/* NAVIGATION ACTIONS */}
export const BACK = 'BACK';
export const TOGGLE_DRAWER = 'TOGGLE_DRAWER';
export const GO_TO_WELCOME = 'GO_TO_WELCOME';
export const GO_TO_LOGIN = 'GO_TO_LOGIN';
export const GO_TO_DASHBOARD = 'GO_TO_DASHBOARD';
export const GO_TO_ACCOUNT = 'GO_TO_ACCOUNT';
export const GO_TO_ACCOUNT_DETAIL = 'GO_TO_ACCOUNT_DETAIL';
export const GO_TO_ACCOUNT_CREATE = 'GO_TO_ACCOUNT_CREATE';
export const GO_TO_VENDOR_LIST = 'GO_TO_VENDOR_LIST';
export const GO_TO_VENDOR_DETAIL = 'GO_TO_VENDOR_DETAIL';
export const GO_TO_BOOKING = 'GO_TO_BOOKING';

{/* ACCOUNT ACTIONS */}
export const ACCOUNT_FORM_INIT = 'ACCOUNT_FORM_INIT';
export const ACCOUNT_UPDATE_PROP = 'ACCOUNT_UPDATE_PROP';
export const ACCOUNT_CREATE = 'ACCOUNT_CREATE';
export const ACCOUNT_CREATE_SUCCESS = 'ACCOUNT_CREATE_SUCCESS';
export const ACCOUNT_CREATE_FAIL = 'ACCOUNT_CREATE_FAIL';

{/* VENDOR ACTIONS */}
export const VENDORS_FETCH = 'VENDORS_FETCH';
export const VENDORS_FETCH_SUCCESS = 'VENDORS_FETCH_SUCCESS';
